server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: meufluxo

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: false

logging:
  level:
    root: INFO

#  jackson:
#    serialization:
#      fail-on-empty-beans: false
#    deserialization:
#      fail-on-unknown-properties: false
#    default-property-inclusion: non_null

#  mvc:
#    locale: pt_BR
#    format:
#      date: yyyy-MM-dd
#      date-time: yyyy-MM-dd'T'HH:mm:ss
#      time: HH:mm:ss
#    throw-exception-if-no-handler-found: true

#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 20MB
#
#server:
#  error:
#    include-message: always
#    include-binding-errors: always
#    whitelabel:
#      enabled: false

#logging:
#  level:
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
