spring:
  datasource:
    url: jdbc:postgresql://${DB_PROD_NAME}:${DB_PROD_PORT}/${DB_PROD_NAME}
    username: ${DB_PROD_USER}
    password: ${DB_PROD_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: false